### ISSUE TITLE
AttributeError: module 'kapre' has no attribute 'datasets'

### ISSUE THREAD

**Issue by mgurunathreddy** [keunwoochoi/mir_deepnet_tutorial#11]
Hi,

I downloaded and placed jamendo dataset in dataset_download/jamendo. 
When I run  

python main_preprocess.py jamendo

I am getting the following error

Traceback (most recent call last):
  File "main_preprocess.py", line 95, in <module>
    main(sys.argv[1])
  File "main_preprocess.py", line 79, in main
    prep_jamendo()
  File "main_preprocess.py", line 62, in prep_jamendo
    srcs_sets, ys_sets = kapre.datasets.load_jamendo(save_path=DIR_JAMENDO_DOWNLOAD,
AttributeError: module 'kapre' has no attribute 'datasets'

**Comment by keunwoochoi** [comment]
Could you pull and try again?

On 14Apr 2018, at 13:31, Gurunath Reddy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I downloaded and placed jamendo dataset in dataset_download/jamendo.
When I run

python main_preprocess.py jamendo

I am getting the following error

Traceback (most recent call last):
File "main_preprocess.py", line 95, in
main(sys.argv[1])
File "main_preprocess.py", line 79, in main
prep_jamendo()
File "main_preprocess.py", line 62, in prep_jamendo
srcs_sets, ys_sets = kapre.datasets.load_jamendo(save_path=DIR_JAMENDO_DOWNLOAD,
AttributeError: module 'kapre' has no attribute 'datasets'

**Comment by mgurunathreddy** [comment]
Hi  Keunwoo Choi,

Thanks for the help. I could not able to install the datasets library. Can you please help me in installing it?
I tried the following with no help

$ pip install datasets

Collecting datasets
  Using cached datasets-0.0.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pme48g8j/datasets/setup.py", line 10, in <module>
        with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
      File "/usr/lib/python3.5/codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-pme48g8j/datasets/DESCRIPTION.rst'
    
$python main_preprocess.py jamendo

Traceback (most recent call last):
  File "main_preprocess.py", line 16, in <module>
    import datasets
ImportError: No module named 'datasets'

**Comment by keunwoochoi** [comment]
Oops.. sorry for confusing you, I added datasets.py now. Could you try once again?

On 14Apr 2018, at 18:08, Gurunath Reddy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Keunwoo Choi,

Thanks for the help. I could not able to install the datasets library. Can you please help me in installing it?
I tried the following with no help

$ pip install datasets

Collecting datasets
Using cached datasets-0.0.9.zip
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in
File "/tmp/pip-build-pme48g8j/datasets/setup.py", line 10, in
with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
File "/usr/lib/python3.5/codecs.py", line 895, in open
file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-pme48g8j/datasets/DESCRIPTION.rst'

$python main_preprocess.py jamendo

Traceback (most recent call last):
File "main_preprocess.py", line 16, in
import datasets
ImportError: No module named 'datasets'

**Comment by mgurunathreddy** [comment]
Hi  Keunwoo,

It worked.
Thank you very much for the Deep MIR tutorial.

**Comment by keunwoochoi** [comment]
Thanks for reporting!
