### ISSUE TITLE
Typos and fix suggestions in Example 1 notebook.

### ISSUE THREAD

**Issue by dansuh17** [keunwoochoi/mir_deepnet_tutorial#4]
Thx for the awesome tutorial 👍 
I have run it on my own, and found some typos and python compatibility issues.

1. this is probably `12 output nodes`?
<img width="836" alt="image" src="https://user-images.githubusercontent.com/14329563/32362950-1efb6d28-c0b0-11e7-8cf6-aff39d73ad79.png">

2. `432 = 36 x 12`,  `36 x 12 + 12`
<img width="616" alt="image" src="https://user-images.githubusercontent.com/14329563/32362966-37dde550-c0b0-11e7-9b1c-201982584fdf.png">

3. `next()` in iters as been renamed to `__next__()` in python 3. If proceeded with this, keras model would give `DataGen is not iterable` error. 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/14329563/32362984-4e15ef3e-c0b0-11e7-8694-e92321f1d299.png">

I have tested this with `Keras==2.0.9`

4. Similarly, calling next iteration have been changed in python3.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/14329563/32363035-8e7cff40-c0b0-11e7-9337-3ae0b244a89a.png">

All `datagen.next()` had to be modified to `next(datagen)` in this cell.

**Comment by keunwoochoi** [comment]
Hey, thanks for spotting them. 
1. I think so.
2. Right.
3. Perhaps I can fix it by simply mapping..
```
__next__ = next
```
4. Correct.

Could you PR these? :) (Also the notebooks seem to have some reproducability issue I think, so obviously they need to be updated.)

**Comment by dansuh17** [comment]
Sure! but do you want python2 compatibility as well? It seems there are some workarounds ([here](http://python-future.org/compatible_idioms.html#custom-iterators)) if you desire.
Otherwise, I can fix the notebooks assuming python 3 :)

**Comment by keunwoochoi** [comment]
Thanks! Yes I’d want it to be compatible to both of them. I don’t think there’d be many issues.

On 5 Nov 2017, at 01:20, Daniel Suh <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure! but do you want python2 compatibility as well? It seems there are some workarounds (here<http://python-future.org/compatible_idioms.html#custom-iterators>) if you desire.
Otherwise, I can fix the notebooks assuming python 3 :)

**Comment by dansuh17** [comment]
@keunwoochoi  It seems that I don't have permission to push a branch to your repo :(
Can you please grant permission for pushing branches and making PRs?
`remote: Permission to keunwoochoi/dl4mir.git denied to deNsuh.
fatal: unable to access 'https://github.com/keunwoochoi/dl4mir.git/': The requested URL returned error: 403`

**Comment by keunwoochoi** [comment]
You're not allowed to directly push but I'd guess you can make a PR? --after forking it and pushing there.

**Comment by pnojai** [comment]
I encountered the issue in Example 1, too. Thanks for the upcoming fix, **deNsuh**. **keunwoochoi**, your repo is very cool.

Jai

**Comment by keunwoochoi** [comment]
@pnojai I thought it was fixed. Could you clarify? Thanks.

**Comment by pnojai** [comment]
@keunwoochoi I just assumed my issue was the same one as the OP because Example 1 didn't open for me either. Maybe I should have opened a new issue or just asked a question.

I'm able to open Example 2 (although I get an error in one of the cells; that's another story I must look into.) On the other hand, when I try to run the Example 1 notebook, this error message pops up.

Unreadable Notebook: .../GitHub/dl4mir/Example 1 - a pitch detection network with Dense layers.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

Jai

**Comment by keunwoochoi** [comment]
Oh, that's right. It's just fixed, please have a look.

**Comment by pnojai** [comment]
@keunwoochoi. Thanks. I got further! The notebook opens for me. I pulled your change into my fork.

Before, it didn't even open. Now it does, but the first cell doesn't complete. I think it's my installation, and I'm going to try it on another computer at home.

I get an error that says I don't have future installed. I suspect this error has nothing to do with the notebook. My enterprise firewall doesn't let me do Anaconda installs and when I try to use pip I get really scary exception output (in red even!) that suggests my installation is messed up. 

This is what I get in the cell, but I'm not done debugging my installation yet...

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-039a4428788e> in <module>()
      3 import librosa
      4 import keras
----> 5 from future.utils import implements_iterator  # for python 2 compatibility for __next__()
      6 from matplotlib import pyplot as plt
      7 

ModuleNotFoundError: No module named 'future'

**Comment by pnojai** [comment]
@keunwoochoi Hey, I'm good. Thank you for your help.

I executed the example on my computer at home. Whatever the issue is that I encountered about not finding the future module, it relates to my crappy Anaconda installation on my computer at work.

Jai
